export enum AssetSortField {
  ASSET_ID = 'simpro_asset_id',
  CUSTOMER_NAME = 'site.customer.name',
  SITE_UPRN = 'site.uprn',
  SITE_NAME = 'site.name',
  SITE_ADDRESS = 'site.address',
  SITE_CONTACT = 'site.primary_site_contact.name',
  NAME = 'name',
  LOCATION = 'location',
  MAKE = 'make',
  MODEL = 'model',
  LAST_TEST_RESULT = 'last_test_result',
  LAST_TEST_DATE = 'last_test_date',
  SERVICE_LEVEL = 'service_level_name',
  NEXT_SERVICE_DATE = 'next_service_date',
  JOB_ORDER_NO = 'job.order_no',
  JOB_CUSTOMER_NAME = 'job_customer.name',
  JOB_COMPLETION_DATE = 'job.completion_date',
  NEXT_SCHEDULE_DATE = 'next_schedule.date',
  JOB_STAGE = 'job.stage',
  JOB_ID = 'job.simpro_job_id',
  LAST_CP2_DATE = 'last_cp12_date'
}
