stages:
  - prepare
  - lint
  - build
  - test
  - deploy

variables:
  CI_PROJECT_NAME: jf-customer-portal-frontend
  DOMAIN: dev.jamesfrewportal.co.uk

cache: &global_cache
  paths:
    - ./node_modules
  policy: pull

.build_template: &build
  stage: build
  image: node:20
  script:
    - npm run-script build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  tags:
    - docker
    - linux

node_dependencies:
  stage: prepare
  image: node:20
  script:
    - npm i --legacy-peer-deps
  cache:
    <<: *global_cache
    policy: pull-push
  tags:
    - docker
    - linux

eslint:
  stage: lint
  image: node:20
  script:
    - npm run-script lint
  tags:
    - docker
    - linux

build_development:
  environment:
    name: 'development'
  <<: *build
  except:
    - production
    - master

build_production:
  environment:
    name: 'production'
  <<: *build
  script:
    - npx ng build -c=production
  only:
    - production

deploy_development:
  image: projects.ronasit.com:4567/docker/ssh
  stage: deploy
  script:
    - rsync -av ./dist/jf-customer-portal-frontend/ ci@209.97.185.115:/var/www/jf-customer-portal-frontend/
  only:
    - development

deploy_production:
  image: projects.ronasit.com:4567/docker/ssh
  stage: deploy
  script:
    - rsync -av ./dist/jf-customer-portal-frontend/ ci@167.99.192.109:/var/www/jf-customer-portal-frontend/
  only:
    - production
