export type AssetRelationType =
  | 'site'
  | 'site.primary_site_contact'
  | 'site.customers'
  | 'site.customer'
  | 'asset_custom_fields'
  | 'asset_attachments'
  | 'asset_test_records'
  | 'asset_test_records.job'
  | 'asset_test_records.asset_test_record_readings'
  | 'asset_test_record'
  | 'job'
  | 'job_customer'
  | 'job.job_no_access_dates'
  | 'next_schedule';
