export enum JobSortField {
  JOB_ID = 'simpro_job_id',
  ORDER_NO = 'order_no',
  CUSTOMER_NAME = 'customer.name',
  SITE_UPRN = 'site.uprn',
  SITE_NAME = 'site.name',
  SITE_ADDRESS = 'site.address',
  POSTCODE = 'site.postal_code',
  COST_CENTER = 'cost_center_name',
  PRIORITY = 'priority',
  STAGE = 'stage',
  STATUS = 'job_status',
  CREATED_DATE = 'date_created',
  MADE_SAFE_DATE = 'made_safe_date',
  COMPLETION_DATE = 'completion_date',
  DUE_DATE = 'due_date',
  APPOINTMENT = 'recent_schedule.date',
  ATTACHMENTS = 'job_attachments_count',
  DESCRIPTION = 'description',
  LOGGED_CREATE_DATE = 'logged_create_date',
  LOGGED_COMPLETION_DATE = 'logged_completion_date'
}
